# Generated by Django 5.1.3 on 2024-12-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_otprequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otprequest',
            old_name='chanel',
            new_name='channel',
        ),
    ]
